driji/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin

import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r"^logout/$", views.logout_views, name='logout'),

    url(r'^my/profile/$', views.my_profile, name='my_profile'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),

    url(r'^terminal/$', views.terminal, name='terminal'),
    url(r'^terminal/scan/$', views.terminal_scan, name='terminal_scan'),
    url(r'^terminal/add$', views.terminal_add, name='terminal_add'),
    url(r'^terminal/(?P<terminal_id>[0-9]+)/$', views.terminal_detail, name='terminal_detail'),
    url(r'^terminal/(?P<action>[\w-]+)/(?P<terminal_id>[0-9]+)/$', views.terminal_action, name='terminal_action'),

    url(r'^student/$', views.student, name='student'),
    url(r'^student/add/terminal$', views.student_add_terminal, name='student_add_terminal'),
    url(r'^student/add/$', views.student_add, name='student_add'),

    url(r'^attendance/(?P<terminal_id>[0-9]+)/$$', views.attendance, name='attendance'),

    url(r'^phonebook/$', views.phonebook, name='phonebook'),

    url(r'^sms/$', views.sms, name='sms'),

    url(r'^settings/grade/$', views.index, name='settings_grade'),
    url(r'^settings/grade/add/$', views.index, name='settings_grade_add')
]

driji/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User as AuthUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

from zkcluster.models import Attendance, ZKBaseUser


class BaseModel(models.Model):
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)

    class Meta:
        abstract = True


class User(BaseModel, ZKBaseUser):
    USER_ADMINISTRATOR = 1
    USER_STAFF = 2
    USER_PARENT = 3
    USER_STUDENT = 4

    USER_TYPE_CHOICES = (
        (USER_ADMINISTRATOR, _('Administrator')),
        (USER_STAFF, _('Staff / Teacher')),
        (USER_PARENT, _('Parent')),
        (USER_STUDENT, _('Student'))
    )

    GENDER_MALE = 'm'
    GENDER_FEMALE = 'f'

    GENDER_CHOICES = (
        (GENDER_MALE, _('male')),
        (GENDER_FEMALE, _('female'))
    )

    auth = models.OneToOneField(AuthUser, related_name='driji_user', blank=True, null=True)
    fullname = models.CharField(_('full name'), max_length=100)
    user_type = models.IntegerField(choices=USER_TYPE_CHOICES, default=USER_STUDENT)
    gender = models.CharField(_('gender'), max_length=1, choices=GENDER_CHOICES, default=GENDER_MALE)
    parent = models.ForeignKey("self", blank=True, null=True)

    NAME_FIELD = 'fullname'

    class Meta:
        db_table = 'driji_user'

    @property
    def gender_name(self):
        if self.gender == self.GENDER_MALE:
            return _('male')
        elif self.gender == self.GENDER_FEMALE:
            return _('female')

    def user_type_name(self):
        if self.user_type == self.USER_ADMINISTRATOR:
            return _('Administrator')
        if self.user_type == self.USER_STAFF:
            return _('Staff')
        if self.user_type == self.USER_PARENT:
            return _('Parent')
        if self.user_type == self.USER_STUDENT:
            return _('Student')

    def __unicode__(self):
        return self.fullname


class PhoneBook(BaseModel):
    address = models.CharField(_('address'), max_length=200, blank=True, null=True)
    phone_number = models.CharField(_('phone number'), max_length=16, unique=True, db_index=True)
    driji_user = models.OneToOneField(User, related_name='ponebook')

    class Meta:
        db_table = 'driji_phonebook'

    def __unicode__(self):
        return self.driji_user.fullname


class AttendanceSummary(BaseModel):
    STATUS_PRESENT = 'p'
    STATUS_ABSENCE = 'a'
    STATUS_LATE = 'l'

    STATUS_CHOICES = (
        (STATUS_PRESENT, _('present')),
        (STATUS_ABSENCE, _('absense')),
        (STATUS_LATE, _('late'))
    )

    driji_user = models.ForeignKey(User, related_name='attendances')
    zk_attendance = models.OneToOneField(Attendance, related_name='summary')
    date = models.DateField()
    status = models.CharField(_('status'), max_length=1, choices=STATUS_CHOICES)

    def save(self, *args, **kwargs):
        timestamp = self.zk_attendance.timestamp
        late_time = timestamp.replace(hour=8, minute=0, microsecond=0)
        if timestamp >= late_time:
            self.status = self.STATUS_LATE
        else:
            self.status = self.STATUS_PRESENT
        super(AttendanceSummary, self).save(*args, **kwargs)

    class Meta:
        db_table = 'driji_attendance_summary'
        unique_together = ('driji_user', 'date')

driji/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User as AuthUser
from django.utils.translation import ugettext as _

from driji.models import PhoneBook, User

from zkcluster.models import Terminal

# from .models import Student, Grade


class LoginForm(forms.Form):
    identifier = forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={
            'placeholder': _('Username or Email'),
            'class': 'form-control'
        }))
    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(attrs={
            'placeholder': _('Password'),
            'class': 'form-control'
        }))

    def clean_identifier(self):
        identifier = self.cleaned_data.get('identifier')

        if '@' in identifier:
            user = AuthUser.objects.filter(email__iexact=identifier).first()
        else:
            user = AuthUser.objects.filter(username__iexact=identifier).first()

        if not user:
            raise forms.ValidationError(_('User does not exists'))

        return user

    def clean(self):
        data = self.cleaned_data
        user = data.get('identifier')
        password = data.get('password')

        if user and password:
            authenticate_user = authenticate(
                username=user.username, password=password)

            if authenticate_user is None:
                err_message = _('Incorrect password')
                self._errors['password'] = self.error_class([err_message])

        return data

    def get_authenticate_user(self):
        data = self.cleaned_data
        username = data.get('identifier').username
        password = data.get('password')

        user = authenticate(username=username, password=password)

        return user


class ScanTerminalForm(forms.Form):
    ip = forms.CharField(
        label=_('IP Address'),
        max_length=15,
        widget=forms.TextInput(attrs={
            'placeholder': '192.168.200.1',
            'class': 'form-control',
        })
    )
    port = forms.IntegerField(
        label=_('Port'),
        widget=forms.TextInput(attrs={
            'value': 4370,
            'class': 'form-control',
        })
    )

    def clean_ip(self):
        ip = self.cleaned_data.get('ip')
        try:
            if self.instance.ip == ip:
                return ip
        except AttributeError:
            pass

        try:
            if self.instance.ip == ip:
                return ip
        except AttributeError:
            pass

        terminal = Terminal.objects.filter(ip__iexact=ip).first()
        if terminal:
            raise forms.ValidationError(_('IP already exists'))
        return ip


class AddTerminalForm(forms.ModelForm, ScanTerminalForm):
    serialnumber = forms.CharField(
        label=_('Serial Number'),
        required=False,
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': _('Serial number'),
            'class': 'form-control',
            'readonly': True
        })
    )
    name = forms.CharField(
        label=_('Name'),
        required=False,
        max_length=200,
        widget=forms.TextInput(attrs={
            'placeholder': _('Terminal name'),
            'class': 'form-control',
        })
    )

    class Meta:
        model = Terminal
        fields = ('ip', 'port', 'serialnumber', 'name')

    def __init__(self, *args, **kwargs):
        super(AddTerminalForm, self).__init__(*args, **kwargs)
        self.validate_name = False
        if len(args) > 1:
            self.validate_name = args[1].get('validate_name')

        self.fields['ip'].widget = forms.TextInput(attrs={
            'placeholder': _('IP Address'),
            'class': 'form-control',
            'readonly': True
        })
        self.fields['port'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'readonly': True
        })

    def clean_serialnumber(self):
        serialnumber = self.cleaned_data.get('serialnumber')
        try:
            if self.instance.serialnumber == serialnumber:
                return serialnumber
        except AttributeError:
            pass

        terminal = Terminal.objects.filter(serialnumber__iexact=serialnumber).first()
        if terminal:
            raise forms.ValidationError(_('Serial number already exists'))
        return serialnumber

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if self.validate_name:
            if not name:
                raise forms.ValidationError(_('This field is required.'))
        return name


class EditTerminalForm(AddTerminalForm):
    def __init__(self, *args, **kwargs):
        super(EditTerminalForm, self).__init__(*args, **kwargs)

        self.fields['ip'].widget = forms.TextInput(attrs={
            'placeholder': _('IP Address'),
            'class': 'form-control'
        })
        self.fields['port'].widget = forms.TextInput(attrs={
            'class': 'form-control'
        })


class StudentForm(forms.Form):
    # student information
    fullname = forms.CharField(
        label=_('full name'),
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': _('full name'),
            'class': 'form-control'
        })
    )
    gender = forms.ChoiceField(
        label=_('gender'),
        choices=User.GENDER_CHOICES,
        widget=forms.Select(attrs={
            'class': 'form-control'
        })
    )
    phone_number = forms.CharField(
        label=_('phone number'),
        max_length=16,
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        })
    )
    address = forms.CharField(
        label=_('address'),
        max_length=200,
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 3
        })
    )
    # parent information
    parent_fullname = forms.CharField(
        label=_('full name'),
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': _('full name'),
            'class': 'form-control'
        })
    )
    parent_gender = forms.ChoiceField(
        label=_('gender'),
        choices=User.GENDER_CHOICES,
        widget=forms.Select(attrs={
            'class': 'form-control'
        })
    )
    parent_phone_number = forms.CharField(
        label=_('phone number'),
        max_length=16,
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        })
    )
    parent_address = forms.CharField(
        label=_('address'),
        max_length=200,
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 3
        })
    )

    def is_phone_number_available(self, phone_number):
        phonebook = PhoneBook.objects.filter(phone_number__iexact=phone_number).first()
        if phonebook:
            return True
        return False

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if self.is_phone_number_available(phone_number):
            raise forms.ValidationError(_('this number already exits'))
        return phone_number

    def clean_parent_phone_number(self):
        phone_number = self.cleaned_data.get('parent_phone_number')
        if self.is_phone_number_available(phone_number):
            raise forms.ValidationError(_('this number already exits'))
        return phone_number

    def clean(self):
        cleaned_data = self.cleaned_data
        phone_number = cleaned_data.get('phone_number')
        parent_phone_number = cleaned_data.get('parent_phone_number')
        if phone_number and parent_phone_number:
            if phone_number.lower() == parent_phone_number.lower():
                err_message = _('phone number should be difference')
                self._errors['phone_number'] = self.error_class([err_message])
                self._errors['parent_phone_number'] = self.error_class([err_message])
        return cleaned_data

    def save(self):
        cleaned_data = self.cleaned_data
        # Parent Information
        parent_fullname = cleaned_data.get('parent_fullname')
        parent_gender = cleaned_data.get('parent_gender')
        parent_phone_number = cleaned_data.get('parent_phone_number')
        parent_address = cleaned_data.get('parent_address')

        new_parent = User.objects.create(
            fullname=parent_fullname,
            user_type=User.USER_PARENT,
            gender=parent_gender
        )
        PhoneBook.objects.create(
            address=parent_address,
            phone_number=parent_phone_number,
            driji_user=new_parent
        )

        # Student Information
        fullname = cleaned_data.get('fullname')
        gender = cleaned_data.get('gender')
        phone_number = cleaned_data.get('phone_number')
        address = cleaned_data.get('address')

        new_student = User.objects.create(
            fullname=fullname,
            user_type=User.USER_STUDENT,
            gender=gender,
            parent=new_parent
        )
        PhoneBook.objects.create(
            address=address,
            phone_number=phone_number,
            driji_user=new_student
        )

        return new_student

driji/templates/phonebook.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ol class="breadcrumb navbar-breadcrumb">
  <li class="active">
    {% trans 'Phonebook' %}
  </li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-xs-12">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="title">
            {% trans 'Contact List' %}
          </div>
        </div>
      </div>
      <div class="card-body" style="margin-bottom: 80px;">
        <table class="table table-striped" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th>{% trans 'Name' %}</th>
              <th>{% trans 'Gender' %}</th>
              <th>{% trans 'Type' %}</th>
              <th>{% trans 'Phone Number' %}</th>
              <th>{% trans 'Address' %}</th>
            </tr>
          </thead>
          <tbody>
            {% for contact in contacts %}
              <tr>
                <td>
                  <a href="{% url 'profile' contact.driji_user.id %}">
                    {{ contact.driji_user.fullname }}
                  </a>
                </td>
                <td>{{ contact.driji_user.gender_name }}</td>
                <td>{{ contact.driji_user.user_type_name }}</td>
                <td>{{ contact.phone_number }}</td>
                <td>{{ contact.address }}</td>
              </tr>
            {% endfor  %}
          </tbody>
        </table>
        <div class="center">
          <button class="btn btn-primary">
            <span class="fa fa-chevron-left"></span>
          </button>
          {% for page in contacts.paginator.page_range %}
            <a href="?page={{ page }}">
              <button class="btn btn-default">{{ page }}</button>
            </a>
          {% endfor %}
          <button class="btn btn-primary">
            <span class="fa fa-chevron-right"></span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
  <script>
    $('.zk_action').click(function(){
      $(this).siblings('form').submit();
    });
  </script>
{% endblock %}

driji/templates/settings_grade_add.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ol class="breadcrumb navbar-breadcrumb">
  <li>
    {% trans 'Settings' %}
  </li>
  <li>
    <a href="{% url 'settings_grade' %}">
      {% trans 'Grade' %}
    </a>
  </li>
  <li class="active">
    {% trans 'New Grade' %}
  </li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        <div class="title">{% trans 'Add New Grade' %}</div>
        </div>
      </div>
      <div class="card-body">
        <div class="panel-body">
          <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
              <span class="error">{{ form.name.errors.0 }}</span>
              {{ form.name }}
            </div>
            <div class="form-group">
              <label for="{{ form.description.auto_id }}">{{ form.description.label }}</label>
              <span class="error">{{ form.description.errors.0 }}</span>
              {{ form.description }}
            </div>
            <button id="id_submit" type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        <div class="title">{% trans 'Info' %}</div>
        </div>
      </div>
      <div class="card-body">
        <div class="panel-body">
          <p>
            {% trans 'Not available' %}
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
  <script>
    $('#id_name').focus();
    $("form").submit(function(){
      $(this).find(":submit").attr("disabled","disabled").html("{% trans 'Saving...' %}");
    });
  </script>
{% endblock %}

driji/templates/student_add.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ol class="breadcrumb navbar-breadcrumb">
  <li>
    <a href="{% url 'student' %}">{% trans 'Student' %}</a>
  </li>
  <li class="active">
    {% trans 'New Student' %}
  </li>
</ol>
{% endblock %}

{% block content %}
<form method="POST" action="">
  {% csrf_token %}
  <div class="row">
    <div class="col-sm-6">
      <div class="card" style="padding-bottom: 45px;">
        <div class="card-header">
          <div class="card-title">
          <div class="title">{% trans 'Student Registration' %}</div>
          </div>
        </div>
        <div class="card-body">
          <div class="panel-body">
            <div class="form-group">
              <label for="{{ form.fullname.auto_id }}">{{ form.fullname.label }}</label>
              <span class="error">{{ form.fullname.errors.0 }}</span>
              {{ form.fullname }}
            </div>
            <div class="form-group">
              <label for="{{ form.gender.auto_id }}">{{ form.gender.label }}</label>
              <span class="error">{{ form.gender.errors.0 }}</span>
              {{ form.gender }}
            </div>
            <div class="form-group">
              <label for="{{ form.phone_number.auto_id }}">{{ form.phone_number.label }}</label>
              <span class="error">{{ form.phone_number.errors.0 }}</span>
              {{ form.phone_number }}
            </div>
            <div class="form-group">
              <label for="{{ form.address.auto_id }}">{{ form.address.label }}</label>
              <span class="error">{{ form.address.errors.0 }}</span>
              {{ form.address }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header">
          <div class="card-title">
          <div class="title">{% trans 'Parent Information' %}</div>
          </div>
        </div>
        <div class="card-body">
          <div class="panel-body">
            <div class="form-group">
              <label for="{{ form.parent_fullname.auto_id }}">{{ form.parent_fullname.label }}</label>
              <span class="error">{{ form.parent_fullname.errors.0 }}</span>
              {{ form.parent_fullname }}
            </div>
            <div class="form-group">
              <label for="{{ form.parent_gender.auto_id }}">{{ form.parent_gender.label }}</label>
              <span class="error">{{ form.parent_gender.errors.0 }}</span>
              {{ form.parent_gender }}
            </div>
            <div class="form-group">
              <label for="{{ form.parent_phone_number.auto_id }}">{{ form.parent_phone_number.label }}</label>
              <span class="error">{{ form.parent_phone_number.errors.0 }}</span>
              {{ form.parent_phone_number }}
            </div>
            <div class="form-group">
              <label for="{{ form.parent_address.auto_id }}">{{ form.parent_address.label }}</label>
              <span class="error">{{ form.parent_address.errors.0 }}</span>
              {{ form.parent_address }}
            </div>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" style="float: right; margin-bottom: 30px; margin-right: 15px;">{% trans 'Save' %}</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block script %}
  <script>
    $('#id_fullname').focus();
    $("form").submit(function(){
      $(this).find(":submit").attr("disabled","disabled").html("{% trans 'Saving...' %}");
    });
  </script>
{% endblock %}

driji/templates/terminal_add.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ol class="breadcrumb navbar-breadcrumb">
  <li>
    <a href="{% url 'terminal' %}">{% trans 'Terminal' %}</a>
  </li>
  <li class="active">
    {% trans 'New Terminal' %}
  </li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        <div class="title">{% trans 'Add a new terminal' %}</div>
        </div>
      </div>
      <div class="card-body">
        <div class="panel-body">
          <form method="POST" action="{% url 'terminal_add' %}?connected=1">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.ip.auto_id }}">{{ form.ip.label }}</label>
              <span class="error">{{ form.ip.errors.0 }}</span>
              {{ form.ip }}
            </div>
            <div class="form-group">
              <label for="{{ form.port.auto_id }}">{{ form.port.label }}</label>
              <span class="error">{{ form.port.errors.0 }}</span>
              {{ form.port }}
            </div>
            <div class="form-group">
              <label for="{{ form.serialnumber.auto_id }}">{{ form.serialnumber.label }}</label>
              <span class="error">{{ form.serialnumber.errors.0 }}</span>
              {{ form.serialnumber }}
            </div>
            <div class="form-group">
              <label for="{{ form.name.auto_id }}">{{ form.name.label }}</label>
              <span class="error">{{ form.name.errors.0 }}</span>
              {{ form.name }}
            </div>
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        <div class="title">{% trans 'Info' %}</div>
        </div>
      </div>
      <div class="card-body">
        <div class="panel-body">
          <p>
            {% trans 'You need to configure the terminal network before save it to system.' %}
          </p>
          <img src="{% static 'img/zksoftware_device.jpg' %}" alt="" width="250px"/>
        </div>
        <div class="sub-title">{% trans 'How To Settings Network' %}</div>
        <div class="panel-body">
          <ol>
            <li>{% trans 'Go to menu by holding the button <strong>OK</strong>' %}</li>
            <li>{% trans 'Select menu <strong>Comm</strong>' %}</li>
            <li>{% trans 'Select sub menu <strong>Network</strong>' %}</li>
            <li>{% trans 'Fill the form and then press <strong>OK</strong>' %}</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
  <script>
    $('#id_name').focus();
    $("form").submit(function(){
      $(this).find(":submit").attr("disabled","disabled").html("{% trans 'Saving...' %}");
    });
  </script>
{% endblock %}

driji/templates/terminal_members.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ol class="breadcrumb navbar-breadcrumb">
  <li class="active">
    <a href="{% url 'terminal' %}">
      {% trans 'Terminal' %}
    </a>
  </li>
  <li>
    {{ terminal.name }}
  </li>
  <li class="active">
    {% trans 'Members' %}
  </li>
</ol>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="card">
        <div class="card-header">
          <div class="card-title">
          <div class="title">
            {% trans 'Member of ' %} {{ terminal.name }}
          </div>
          </div>
        </div>
        <div class="card-body" style="margin-bottom: 80px;">
          <table class="table table-striped" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>{% trans 'ID' %}</th>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Gender' %}</th>
                <th>{% trans 'Parent' %}</th>
              </tr>
            </thead>
            <tbody>
              {% for user in terminal.user_set.all %}
                <tr>
                  <td>{{ user.id }}</td>
                  <td>{{ user.fullname }}</td>
                  <td>{{ user.gender_name }}</td>
                  <td>{{ user.parent.fullname }}</td>
                </tr>
              {% endfor  %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

driji/templates/terminal_scan.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block breadcrumb %}
<ol class="breadcrumb navbar-breadcrumb">
  <li>
    <a href="{% url 'terminal' %}">{% trans 'Terminal' %}</a>
  </li>
  <li class="active">
    {% trans 'Scan' %}
  </li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        <div class="title">{% trans 'Scan a terminal' %}</div>
        </div>
      </div>
      <div class="card-body">
        <div class="panel-body">
          <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.email.auto_id }}">{{ form.ip.label }}</label>
              <span class="error">{{ form.ip.errors.0 }}</span>
              {{ form.ip }}
            </div>
            <div class="form-group">
              <label for="{{ form.port.auto_id }}">{{ form.port.label }}</label>
              <span class="error">{{ form.port.errors.0 }}</span>
              {{ form.port }}
            </div>
            <button id="id_submit" type="submit" class="btn btn-primary">{% trans 'Scan' %}</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
        <div class="title">{% trans 'Info' %}</div>
        </div>
      </div>
      <div class="card-body">
        <div class="panel-body">
          <p>
            {% trans 'You need to configure the terminal network before save it to system.' %}
          </p>
          <img src="{% static 'img/zksoftware_device.jpg' %}" alt="" width="250px"/>
        </div>
        <div class="sub-title">{% trans 'How To Settings Network' %}</div>
        <div class="panel-body">
          <ol>
            <li>{% trans 'Go to menu by holding the button <strong>OK</strong>' %}</li>
            <li>{% trans 'Select menu <strong>Comm</strong>' %}</li>
            <li>{% trans 'Select sub menu <strong>Network</strong>' %}</li>
            <li>{% trans 'Fill the form and then press <strong>OK</strong>' %}</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
  <script>
    $("#id_ip").focus();
    $("form").submit(function(){
      $(this).find(":submit").attr("disabled","disabled").html("{% trans 'Scanning...' %}");
    });
  </script>
{% endblock %}